name: Release (cargo-dist)

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  plan:
    runs-on: ubuntu-latest
    outputs:
      dist-version: ${{ steps.plan.outputs.dist-version }}
      tasks: ${{ steps.plan.outputs.tasks }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
      - name: Install cargo-dist (prebuilt)
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-dist
      - name: Ensure cargo-dist available
        run: |
          echo "PATH=$PATH"
          if ! command -v cargo-dist >/dev/null 2>&1; then
            echo "cargo-dist not found; installing via cargo";
            cargo install cargo-dist --locked;
          fi
          cargo-dist --version
      - id: plan
        run: |
          cargo-dist plan --tag ${{ github.ref_name }} --output-format json > dist-plan.json
          echo "dist-version=$(jq -r .dist_version dist-plan.json)" >> $GITHUB_OUTPUT
          echo "tasks=$(jq -c .tasks dist-plan.json)" >> $GITHUB_OUTPUT

  build:
    needs: plan
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-13
            target: x86_64-apple-darwin
          - os: macos-14
            target: aarch64-apple-darwin
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Install build deps (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y clang llvm-dev libclang-dev pkg-config
      - name: Install cargo-dist (prebuilt)
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-dist@${{ needs.plan.outputs.dist-version }}
      - name: Ensure cargo-dist available
        run: |
          if ! command -v cargo-dist >/dev/null 2>&1; then
            cargo install cargo-dist --locked;
          fi
          cargo-dist --version
      - name: Build Artifacts
        run: |
          cargo-dist build --target ${{ matrix.target }} --tag ${{ github.ref_name }}
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-${{ matrix.target }}
          path: target/distrib/*

  upload:
    needs: [plan, build]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-dist@${{ needs.plan.outputs.dist-version }}
      - name: Ensure cargo-dist available
        run: |
          if ! command -v cargo-dist >/dev/null 2>&1; then
            cargo install cargo-dist --locked;
          fi
          cargo-dist --version
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: artifacts-*
          merge-multiple: true
      - name: Upload to Release
        env:
          # GitHub-provided token for this repo
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          cargo-dist upload --tag ${{ github.ref_name }} target/distrib/*

  publish-tap:
    needs: [plan, upload]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-dist@${{ needs.plan.outputs.dist-version }}
      - name: Ensure cargo-dist available
        run: |
          if ! command -v cargo-dist >/dev/null 2>&1; then
            cargo install cargo-dist --locked;
          fi
          cargo-dist --version
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: artifacts-*
          merge-multiple: true
      - name: Publish Homebrew Tap PR
        env:
          # Default repo token (works if tap is same owner and permissions suffice)
          GITHUB_TOKEN: ${{ github.token }}
          # Optional PAT for cross-repo write; if present will override GITHUB_TOKEN below.
          TAP_TOKEN: ${{ secrets.HOMEBREW_TAP_TOKEN }}
        run: |
          # Prefer TAP_TOKEN if provided
          if [ -n "${TAP_TOKEN}" ]; then export GITHUB_TOKEN="${TAP_TOKEN}"; fi
          cargo-dist publish --installer homebrew --tag ${{ github.ref_name }}
